## Import libraries

In [16]:
import os
from glob import glob
from pathlib import Path
import numpy as np
import pandas as pd
import torch
from torch.utils.data import Dataset, DataLoader
import torchcrop
from torchcrop import (
    CropParameters,
    SoilParameters,
    SiteParameters,
    Lintul5Model,
    WeatherDriver
)

DATA_DIR = Path("data", "brandenburg", "torchcrop")

In [ ]:
class TorchCropDataset(Dataset):
    def __init__(self, weather_dir, soil_dir, site_dir):
        super().__init__()
        self.weather_dir = weather_dir
        self.soil_data = pd.read_csv(os.path.join(soil_dir, "soil.csv")).set_index("location")
        # self.site_data = pd.read_csv(os.path.join(site_dir, "site.csv"))
        self.locations = self.soil_data.index
        
    def __len__(self):
        return len(self.locations)
        
    def __getitem__(self, idx):
        
        # Prepare weather data
        # ----------------------------------------------------------------------------------
        weather_data = pd.read_csv(os.path.join(self.weather_dir, f"{idx}.csv"), parse_dates=["Date"])
        weather_data["Radiation"] = weather_data["Radiation"] / 1000.0      # Convert radiation unit from kJ to MJ
        weather_data["Date"] = weather_data["Date"].dt.dayofyear            # Convert date to DOY
        weather_data = weather_data.values                                  # Final weather array

        # Prepare soil data
        # ----------------------------------------------------------------------------------
        soil_over = dict(
            wcad=sc(srow["SMDRY"]),     # air-dry water content
            wcwp=sc(srow["SMW"]),       # wilting point
            wcfc=sc(srow["SMFC"]),      # field capacity
            wcst=sc(srow["SM0"]),       # saturation
            crairc=sc(srow["CRAIRC"]),  # critical air content
            wci=sc(srow["SMI"]),        # initial root-zone moisture
            wci_lower=sc(srow["SMLOWI"]),
            rdmso=sc(srow["RDMSO"]),    # max rooting depth from soil [m]
            runfr=sc(srow["RUNFR"]),
            cfev=sc(srow["CFEV"]),
            ksub=sc(srow["KSUB"]),
            irri=sc(CFG["irri"]),       # no irrigation
        )
        
        return weather_data

In [83]:
dataset = TorchCropDataset(
    weather_dir=DATA_DIR / "weather",
    soil_dir=DATA_DIR / "soil",
    site_dir=DATA_DIR / "site"
)

dataloader = DataLoader(
    dataset,
    batch_size=4,
    shuffle=True,
)

In [87]:
dataset.soil_data

,SMDRY,SMW,SMFC,SMO,CRAIRC,SMI,SMLOWI,RDMSO,RUNFR,CFEV,KSUB
location,,,,,,,,,,,
0,0.026275,0.052550,0.132392,0.375575,0.07,0.132392,0.132392,2,0,2,100
1,0.028806,0.057611,0.148077,0.391740,0.07,0.148077,0.148077,2,0,2,100
2,0.061266,0.122533,0.239435,0.416913,0.07,0.239435,0.239435,2,0,2,100
3,0.016730,0.033460,0.079727,0.372395,0.07,0.079727,0.079727,2,0,2,100
4,0.039435,0.078871,0.178746,0.364946,0.07,0.178746,0.178746,2,0,2,100
5,0.041183,0.082366,0.154016,0.404326,0.07,0.154016,0.154016,2,0,2,100
6,0.020010,0.040021,0.100029,0.335405,0.07,0.100029,0.100029,2,0,2,100
7,0.027342,0.054683,0.128910,0.385821,0.07,0.128910,0.128910,2,0,2,100
8,0.021794,0.043587,0.096162,0.352463,0.07,0.096162,0.096162,2,0,2,100
9,0.029174,0.058347,0.122051,0.322010,0.07,0.122051,0.122051,2,0,2,100
10,0.016448,0.032896,0.077702,0.410698,0.07,0.077702,0.077702,2,0,2,100
11,0.117741,0.235483,0.351047,0.453818,0.07,0.351047,0.351047,2,0,2,100
12,0.022187,0.044374,0.113859,0.364167,0.07,0.113859,0.113859,2,0,2,100
13,0.015188,0.030377,0.075077,0.384982,0.07,0.075077,0.075077,2,0,2,100
14,0.049560,0.099120,0.244366,0.480145,0.07,0.244366,0.244366,2,0,2,100
15,0.024519,0.049038,0.113206,0.343752,0.07,0.113206,0.113206,2,0,2,100
16,0.019043,0.038087,0.099426,0.375704,0.07,0.099426,0.099426,2,0,2,100
17,0.015914,0.031827,0.076712,0.383006,0.07,0.076712,0.076712,2,0,2,100

In [ ]:
dataset.soil_data.set_index("location").iloc

SMDRY       0.028806
SMW         0.057611
SMFC        0.148077
SMO         0.391740
CRAIRC      0.070000
SMI         0.148077
SMLOWI      0.148077
RDMSO       2.000000
RUNFR       0.000000
CFEV        2.000000
KSUB      100.000000
Name: 1, dtype: float64

In [73]:
batch = next(iter(dataloader))

In [74]:
WeatherDriver(batch).data[0][:, 0]

tensor([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.,  11.,  12.,
         13.,  14.,  15.,  16.,  17.,  18.,  19.,  20.,  21.,  22.,  23.,  24.,
         25.,  26.,  27.,  28.,  29.,  30.,  31.,  32.,  33.,  34.,  35.,  36.,
         37.,  38.,  39.,  40.,  41.,  42.,  43.,  44.,  45.,  46.,  47.,  48.,
         49.,  50.,  51.,  52.,  53.,  54.,  55.,  56.,  57.,  58.,  59.,  60.,
         61.,  62.,  63.,  64.,  65.,  66.,  67.,  68.,  69.,  70.,  71.,  72.,
         73.,  74.,  75.,  76.,  77.,  78.,  79.,  80.,  81.,  82.,  83.,  84.,
         85.,  86.,  87.,  88.,  89.,  90.,  91.,  92.,  93.,  94.,  95.,  96.,
         97.,  98.,  99., 100., 101., 102., 103., 104., 105., 106., 107., 108.,
        109., 110., 111., 112., 113., 114., 115., 116., 117., 118., 119., 120.,
        121., 122., 123., 124., 125., 126., 127., 128., 129., 130., 131., 132.,
        133., 134., 135., 136., 137., 138., 139., 140., 141., 142., 143., 144.,
        145., 146., 147., 148., 149., 150., 151., 152., 153., 154., 155., 156.,
        157., 158., 159., 160., 161., 162., 163., 164., 165., 166., 167., 168.,
        169., 170., 171., 172., 173., 174., 175., 176., 177., 178., 179., 180.,
        181., 182., 183., 184., 185., 186., 187., 188., 189., 190., 191., 192.,
        193., 194., 195., 196., 197., 198., 199., 200., 201., 202., 203., 204.,
        205., 206., 207., 208., 209., 210., 211., 212., 213., 214., 215., 216.,
        217., 218., 219., 220., 221., 222., 223., 224., 225., 226., 227., 228.,
        229., 230., 231., 232., 233., 234., 235., 236., 237., 238., 239., 240.,
        241., 242., 243., 244., 245., 246., 247., 248., 249., 250., 251., 252.,
        253., 254., 255., 256., 257., 258., 259., 260., 261., 262., 263., 264.,
        265., 266., 267., 268., 269., 270., 271., 272., 273., 274., 275., 276.,
        277., 278., 279., 280., 281., 282., 283., 284., 285., 286., 287., 288.,
        289., 290., 291., 292., 293., 294., 295., 296., 297., 298., 299., 300.,
        301., 302., 303., 304., 305., 306., 307., 308., 309., 310., 311., 312.,
        313., 314., 315., 316., 317., 318., 319., 320., 321., 322., 323., 324.,
        325., 326., 327., 328., 329., 330., 331., 332., 333., 334., 335., 336.,
        337., 338., 339., 340., 341., 342., 343., 344., 345., 346., 347., 348.,
        349., 350., 351., 352., 353., 354., 355., 356., 357., 358., 359., 360.,
        361., 362., 363., 364., 365., 366.,   1.,   2.,   3.,   4.,   5.,   6.,
          7.,   8.,   9.,  10.,  11.,  12.,  13.,  14.,  15.,  16.,  17.,  18.,
         19.,  20.,  21.,  22.,  23.,  24.,  25.,  26.,  27.,  28.,  29.,  30.,
         31.,  32.,  33.,  34.,  35.,  36.,  37.,  38.,  39.,  40.,  41.,  42.,
         43.,  44.,  45.,  46.,  47.,  48.,  49.,  50.,  51.,  52.,  53.,  54.,
         55.,  56.,  57.,  58.,  59.,  60.,  61.,  62.,  63.,  64.,  65.,  66.,
         67.,  68.,  69.,  70.,  71.,  72.,  73.,  74.,  75.,  76.,  77.,  78.,
         79.,  80.,  81.,  82.,  83.,  84.,  85.,  86.,  87.,  88.,  89.,  90.,
         91.,  92.,  93.,  94.,  95.,  96.,  97.,  98.,  99., 100., 101., 102.,
        103., 104., 105., 106., 107., 108., 109., 110., 111., 112., 113., 114.,
        115., 116., 117., 118., 119., 120., 121., 122., 123., 124., 125., 126.,
        127., 128., 129., 130., 131., 132., 133., 134., 135., 136., 137., 138.,
        139., 140., 141., 142., 143., 144., 145., 146., 147., 148., 149., 150.,
        151., 152., 153., 154., 155., 156., 157., 158., 159., 160., 161., 162.,
        163., 164., 165., 166., 167., 168., 169., 170., 171., 172., 173., 174.,
        175., 176., 177., 178., 179., 180., 181., 182., 183., 184., 185., 186.,
        187., 188., 189., 190., 191., 192., 193., 194., 195., 196., 197., 198.,
        199., 200., 201., 202., 203., 204., 205., 206., 207., 208., 209., 210.,
        211., 212., 213., 214., 215., 216., 217., 218., 219., 220., 221., 222.,
        223., 224., 225., 226., 227., 228., 229., 230., 231., 232., 233., 234.,
        235., 236., 237., 238., 239., 240., 241., 242., 243., 244., 245., 246.,
        247., 248., 249., 250., 251., 252., 253., 254., 255., 256., 257., 258.,
        259., 260., 261., 262., 263., 264., 265., 266., 267., 268., 269., 270.,
        271., 272., 273., 274., 275., 276., 277., 278., 279., 280., 281., 282.,
        283., 284., 285., 286., 287., 288., 289., 290., 291., 292., 293., 294.,
        295., 296., 297., 298., 299., 300., 301., 302., 303., 304., 305., 306.,
        307., 308., 309., 310., 311., 312., 313., 314., 315., 316., 317., 318.,
        319., 320., 321., 322., 323., 324., 325., 326., 327., 328., 329., 330.,
        331., 332., 333., 334., 335., 336., 337., 338., 339., 340., 341., 342.,
        343., 344., 345., 346., 347., 348., 349., 350., 351., 352., 353., 354.,
        355., 356., 357., 358., 359., 360., 361., 362., 363., 364., 365.],
       dtype=torch.float64)

In [ ]:
weather.data[0][:, 0]

In [62]:
batch.shape

torch.Size([8, 730, 8])

In [55]:
help(DataLoader)

Help on class DataLoader in module torch.utils.data.dataloader:

class DataLoader(typing.Generic)
 |  DataLoader(dataset: 'Dataset[_T_co]', batch_size: 'int | None' = 1, shuffle: 'bool | None' = None, sampler: 'Sampler | Iterable | None' = None, batch_sampler: 'Sampler[list] | Iterable[list] | None' = None, num_workers: 'int' = 0, collate_fn: '_collate_fn_t | None' = None, pin_memory: 'bool' = False, drop_last: 'bool' = False, timeout: 'float' = 0, worker_init_fn: '_worker_init_fn_t | None' = None, multiprocessing_context=None, generator=None, *, prefetch_factor: 'int | None' = None, persistent_workers: 'bool' = False, pin_memory_device: 'str' = '', in_order: 'bool' = True) -> 'None'
 |
 |  Data loader combines a dataset and a sampler, and provides an iterable over the given dataset.
 |
 |  The :class:`~torch.utils.data.DataLoader` supports both map-style and
 |  iterable-style datasets with single- or multi-process loading, customizing
 |  loading order and optional automatic batching (collation) and memory pinning.
 |
 |  See :py:mod:`torch.utils.data` documentation page for more details.
 |
 |  Args:
 |      dataset (Dataset): dataset from which to load the data.
 |      batch_size (int, optional): how many samples per batch to load
 |          (default: ``1``).
 |      shuffle (bool, optional): set to ``True`` to have the data reshuffled
 |          at every epoch (default: ``False``).
 |      sampler (Sampler or Iterable, optional): defines the strategy to draw
 |          samples from the dataset. Can be any ``Iterable`` with ``__len__``
 |          implemented. If specified, :attr:`shuffle` must not be specified.
 |      batch_sampler (Sampler or Iterable, optional): like :attr:`sampler`, but
 |          returns a batch of indices at a time. Mutually exclusive with
 |          :attr:`batch_size`, :attr:`shuffle`, :attr:`sampler`,
 |          and :attr:`drop_last`.
 |      num_workers (int, optional): how many subprocesses to use for data
 |          loading. ``0`` means that the data will be loaded in the main process.
 |          (default: ``0``)
 |      collate_fn (Callable, optional): merges a list of samples to form a
 |          mini-batch of Tensor(s).  Used when using batched loading from a
 |          map-style dataset.
 |      pin_memory (bool, optional): If ``True``, the data loader will copy Tensors
 |          into device/CUDA pinned memory before returning them.  If your data elements
 |          are a custom type, or your :attr:`collate_fn` returns a batch that is a custom type,
 |          see the example below.
 |      drop_last (bool, optional): set to ``True`` to drop the last incomplete batch,
 |          if the dataset size is not divisible by the batch size. If ``False`` and
 |          the size of dataset is not divisible by the batch size, then the last batch
 |          will be smaller. (default: ``False``)
 |      timeout (numeric, optional): if positive, the timeout value for collecting a batch
 |          from workers. Should always be non-negative. (default: ``0``)
 |      worker_init_fn (Callable, optional): If not ``None``, this will be called on each
 |          worker subprocess with the worker id (an int in ``[0, num_workers - 1]``) as
 |          input, after seeding and before data loading. (default: ``None``)
 |      multiprocessing_context (str or multiprocessing.context.BaseContext, optional): If
 |          ``None``, the default
 |          `multiprocessing context <https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods>`_ # noqa: D401
 |          of your operating system will
 |          be used. (default: ``None``)
 |      generator (torch.Generator, optional): If not ``None``, this RNG will be used
 |          by RandomSampler to generate random indexes and multiprocessing to generate
 |          ``base_seed`` for workers. (default: ``None``)
 |      prefetch_factor (int, optional, keyword-only arg): Number of batches loaded
 |          in advance by each worker. ``2`` means there will be a total of
 |          2 * num_workers batches prefetched across all workers. (default value depends
 |          on the set value for num_workers. If value of num_workers=0 default is ``None``.
 |          Otherwise, if value of ``num_workers > 0`` default is ``2``).
 |      persistent_workers (bool, optional): If ``True``, the data loader will not shut down
 |          the worker processes after a dataset has been consumed once. This allows to
 |          maintain the workers `Dataset` instances alive. (default: ``False``)
 |      pin_memory_device (str, optional): Deprecated, the current :ref:`accelerator<accelerators>`
 |          will be used as the device if ``pin_memory=True``.
 |      in_order (bool, optional): If ``False``, the data loader will not enforce that batches
 |          are returned in a first-in, first-out order. Only applies when ``num_workers > 0``. (default: ``True``)
 |
 |
 |  .. warning:: If the ``spawn`` start method is used, :attr:`worker_init_fn`
 |               cannot be an unpicklable object, e.g., a lambda function. See
 |               :ref:`multiprocessing-best-practices` on more details related
 |               to multiprocessing in PyTorch.
 |
 |  .. warning:: ``len(dataloader)`` heuristic is based on the length of the sampler used.
 |               When :attr:`dataset` is an :class:`~torch.utils.data.IterableDataset`,
 |               it instead returns an estimate based on ``len(dataset) / batch_size``, with proper
 |               rounding depending on :attr:`drop_last`, regardless of multi-process loading
 |               configurations. This represents the best guess PyTorch can make because PyTorch
 |               trusts user :attr:`dataset` code in correctly handling multi-process
 |               loading to avoid duplicate data.
 |
 |               However, if sharding results in multiple workers having incomplete last batches,
 |               this estimate can still be inaccurate, because (1) an otherwise complete batch can
 |               be broken into multiple ones and (2) more than one batch worth of samples can be
 |               dropped when :attr:`drop_last` is set. Unfortunately, PyTorch can not detect such
 |               cases in general.
 |
 |               See `Dataset Types`_ for more details on these two types of datasets and how
 |               :class:`~torch.utils.data.IterableDataset` interacts with
 |               `Multi-process data loading`_.
 |
 |  .. warning:: See :ref:`reproducibility`, and :ref:`dataloader-workers-random-seed`, and
 |               :ref:`data-loading-randomness` notes for random seed related questions.
 |
 |  .. warning:: Setting `in_order` to `False` can harm reproducibility and may lead to a skewed data
 |               distribution being fed to the trainer in cases with imbalanced data.
 |
 |  Method resolution order:
 |      DataLoader
 |      typing.Generic
 |      builtins.object
 |
 |  Methods defined here:
 |
 |  __init__(self, dataset: 'Dataset[_T_co]', batch_size: 'int | None' = 1, shuffle: 'bool | None' = None, sampler: 'Sampler | Iterable | None' = None, batch_sampler: 'Sampler[list] | Iterable[list] | None' = None, num_workers: 'int' = 0, collate_fn: '_collate_fn_t | None' = None, pin_memory: 'bool' = False, drop_last: 'bool' = False, timeout: 'float' = 0, worker_init_fn: '_worker_init_fn_t | None' = None, multiprocessing_context=None, generator=None, *, prefetch_factor: 'int | None' = None, persistent_workers: 'bool' = False, pin_memory_device: 'str' = '', in_order: 'bool' = True) -> 'None'
 |      Initialize self.  See help(type(self)) for accurate signature.
 |
 |  __iter__(self) -> '_BaseDataLoaderIter'
 |
 |  __len__(self) -> 'int'
 |
 |  __setattr__(self, attr, val) -> 'None'
 |      Implement setattr(self, name, value).
 |
 |  check_worker_number_rationality(self) -> 'None'
 |
 |  ----------------------------------------------------------------------
 |  Data descriptors defined here:
 |
 |  __dict__
 |      dictionary for instance variables (if defined)
 |
 |  __weakref__
 |      list of weak references to the object (if defined)
 |
 |  multiprocessing_context
 |
 |  ----------------------------------------------------------------------
 |  Data and other attributes defined here:
 |
 |  __annotations__ = {'_iterator': '_BaseDataLoaderIter | None', 'batch_s...
 |
 |  __orig_bases__ = (typing.Generic[+_T_co],)
 |
 |  __parameters__ = (+_T_co,)
 |
 |  ----------------------------------------------------------------------
 |  Class methods inherited from typing.Generic:
 |
 |  __class_getitem__(params) from builtins.type
 |
 |  __init_subclass__(*args, **kwargs) from builtins.type
 |      This method is called when a class is subclassed.
 |
 |      The default implementation does nothing. It may be
 |      overridden to extend subclasses.

In [ ]:
dataset.soil_data.loc[]

,location,SMDRY,SMW,SMFC,SMO,CRAIRC,SMI,SMLOWI,RDMSO,RUNFR,CFEV,KSUB
0,0,0.026275,0.052550,0.132392,0.375575,0.07,0.132392,0.132392,2,0,2,100
1,1,0.028806,0.057611,0.148077,0.391740,0.07,0.148077,0.148077,2,0,2,100
2,2,0.061266,0.122533,0.239435,0.416913,0.07,0.239435,0.239435,2,0,2,100
3,3,0.016730,0.033460,0.079727,0.372395,0.07,0.079727,0.079727,2,0,2,100
4,4,0.039435,0.078871,0.178746,0.364946,0.07,0.178746,0.178746,2,0,2,100
5,5,0.041183,0.082366,0.154016,0.404326,0.07,0.154016,0.154016,2,0,2,100
6,6,0.020010,0.040021,0.100029,0.335405,0.07,0.100029,0.100029,2,0,2,100
7,7,0.027342,0.054683,0.128910,0.385821,0.07,0.128910,0.128910,2,0,2,100
8,8,0.021794,0.043587,0.096162,0.352463,0.07,0.096162,0.096162,2,0,2,100
9,9,0.029174,0.058347,0.122051,0.322010,0.07,0.122051,0.122051,2,0,2,100
10,10,0.016448,0.032896,0.077702,0.410698,0.07,0.077702,0.077702,2,0,2,100
11,11,0.117741,0.235483,0.351047,0.453818,0.07,0.351047,0.351047,2,0,2,100
12,12,0.022187,0.044374,0.113859,0.364167,0.07,0.113859,0.113859,2,0,2,100
13,13,0.015188,0.030377,0.075077,0.384982,0.07,0.075077,0.075077,2,0,2,100
14,14,0.049560,0.099120,0.244366,0.480145,0.07,0.244366,0.244366,2,0,2,100
15,15,0.024519,0.049038,0.113206,0.343752,0.07,0.113206,0.113206,2,0,2,100
16,16,0.019043,0.038087,0.099426,0.375704,0.07,0.099426,0.099426,2,0,2,100
17,17,0.015914,0.031827,0.076712,0.383006,0.07,0.076712,0.076712,2,0,2,100

In [51]:
dataset[1]

array([[ 1.00e+00,  2.10e+00, -2.10e+00, ...,  0.00e+00,  5.10e-01,
         1.80e+00],
       [ 2.00e+00,  9.00e-01, -2.70e+00, ...,  0.00e+00,  5.00e-01,
         2.20e+00],
       [ 3.00e+00,  3.90e+00,  8.00e-01, ...,  4.00e+00,  6.40e-01,
         3.60e+00],
       ...,
       [ 3.63e+02,  1.70e+00,  1.00e-01, ...,  0.00e+00,  6.00e-01,
         2.50e+00],
       [ 3.64e+02,  7.10e+00,  9.00e-01, ...,  1.80e+00,  6.60e-01,
         3.50e+00],
       [ 3.65e+02,  1.23e+01,  1.10e+01, ...,  1.60e+00,  1.26e+00,
         3.80e+00]], shape=(730, 8))

In [52]:
len(dataset)

18